import {
  ArrowLeft,
  AlertTriangle,
  Clock,
  Zap,
  User,
  Route,
  Package,
  TrendingDown,
  Info,
  CheckCircle,
  XCircle,
  AlertCircle,
  Eye,
  FileWarning,
  DollarSign,
  Radio,
  Navigation,
  MapPin,
  Calendar,
  Activity,
  ChevronRight
} from 'lucide-react';

interface AlertDetailScreenProps {
  alertId: string;
  onBack: () => void;
  onOpenRoute?: (routeId: string) => void;
  onOpenDelivery?: (deliveryId: string) => void;
  onOpenDriver?: (driverId: string) => void;
  onOpenRecovery?: () => void;
}

type AlertStatus = 'open' | 'in-review' | 'escalated' | 'closed';
type SeverityLevel = 'low' | 'medium' | 'high' | 'critical';

export function AlertDetailScreen({
  alertId,
  onBack,
  onOpenRoute,
  onOpenDelivery,
  onOpenDriver,
  onOpenRecovery
}: AlertDetailScreenProps) {
  // Mock alert data
  const alert = {
    id: alertId,
    alertId: 'ALT-2847-001',
    alertType: 'SLA Risk',
    severity: 'critical' as SeverityLevel,
    status: 'open' as AlertStatus,
    detectedAt: '10:42 AM',
    detectedMinutesAgo: 8,
    primaryRiskDriver: 'Route running 12 minutes behind schedule with VIP delivery at risk',
    description: 'Critical SLA breach risk detected for high-value customer delivery on Route RT-2847',
    
    // Impacted entities
    impactedRoutes: [
      {
        id: 'RT-2847',
        name: 'Route RT-2847',
        status: 'delayed',
        delayMinutes: 12,
        stopsAtRisk: 3
      }
    ],
    impactedDeliveries: [
      {
        id: 'DEL-8472',
        stopId: 'ST-2847-08',
        customerName: 'Acme Corporation',
        priorityLevel: 'vip',
        slaWindow: '11:00 AM - 12:00 PM',
        timeToBreachMinutes: 18,
        penaltyExposure: '$2,500',
        contractValue: '$150K annual'
      },
      {
        id: 'DEL-8491',
        stopId: 'ST-2847-12',
        customerName: 'Tech Solutions Ltd',
        priorityLevel: 'high',
        slaWindow: '12:30 PM - 1:30 PM',
        timeToBreachMinutes: 68,
        penaltyExposure: '$1,200'
      }
    ],
    impactedDrivers: [
      {
        id: 'DRV-247',
        name: 'Driver #247',
        status: 'active',
        currentLoad: '18/23 stops completed'
      }
    ],
    
    // Evidence & Context
    evidence: {
      snapshotTime: '10:42 AM',
      keySignals: [
        {
          id: 'sig-1',
          label: 'Route Delay Accumulation',
          value: '+12 minutes behind planned schedule',
          severity: 'critical',
          explanation: 'Cumulative delays from previous stops compound risk for remaining deliveries'
        },
        {
          id: 'sig-2',
          label: 'Traffic Anomaly',
          value: 'Heavy congestion on Market St corridor',
          severity: 'high',
          explanation: 'Real-time traffic data shows 8-12 minute delays on primary route corridor'
        },
        {
          id: 'sig-3',
          label: 'VIP Delivery Risk',
          value: '18 minutes to SLA breach',
          severity: 'critical',
          explanation: 'High-value customer delivery approaching SLA window end with current delays'
        },
        {
          id: 'sig-4',
          label: 'Driver Status',
          value: 'Active - No driver-side issues detected',
          severity: 'low',
          explanation: 'Driver is on schedule with normal break patterns and no behavioral flags'
        }
      ],
      systemNotes: [
        'Alert automatically generated by SLA Risk Monitor at 10:42 AM',
        'Traffic data integrated from real-time city traffic APIs',
        'VIP customer flagged in system with high penalty exposure',
        'Route has 5 remaining stops with 3 marked as time-sensitive'
      ]
    },
    
    // Timeline
    timeline: [
      {
        id: 'tl-1',
        timestamp: '10:42 AM',
        event: 'Alert Detected',
        description: 'System identified SLA risk based on route delays and traffic conditions',
        status: 'completed',
        icon: 'alert'
      },
      {
        id: 'tl-2',
        timestamp: '10:42 AM',
        event: 'Alert Created',
        description: 'Alert ALT-2847-001 created with Critical severity',
        status: 'completed',
        icon: 'create'
      },
      {
        id: 'tl-3',
        timestamp: '10:43 AM',
        event: 'Notification Sent',
        description: 'Critical alert notification sent to Dispatch Manager dashboard',
        status: 'completed',
        icon: 'notification'
      },
      {
        id: 'tl-4',
        timestamp: 'Now',
        event: 'Under Review',
        description: 'Alert opened for investigation by dispatch team',
        status: 'current',
        icon: 'review'
      }
    ],
    
    // Risk summary
    riskSummary: {
      totalPenaltyExposure: '$3,700',
      totalDeliveriesAtRisk: 2,
      worstTimeToBreachMinutes: 18,
      affectedVIPCount: 1
    }
  };

  const getStatusBadge = (status: AlertStatus) => {
    switch (status) {
      case 'open':
        return (
          <span className="inline-flex items-center gap-2 px-3 py-1.5 bg-red-100 text-red-700 rounded-lg border border-red-300">
            <Radio className="w-4 h-4" />
            Open
          </span>
        );
      case 'in-review':
        return (
          <span className="inline-flex items-center gap-2 px-3 py-1.5 bg-blue-100 text-blue-700 rounded-lg border border-blue-300">
            <Eye className="w-4 h-4" />
            In Review
          </span>
        );
      case 'escalated':
        return (
          <span className="inline-flex items-center gap-2 px-3 py-1.5 bg-amber-100 text-amber-700 rounded-lg border border-amber-300">
            <AlertTriangle className="w-4 h-4" />
            Escalated
          </span>
        );
      case 'closed':
        return (
          <span className="inline-flex items-center gap-2 px-3 py-1.5 bg-green-100 text-green-700 rounded-lg border border-green-300">
            <CheckCircle className="w-4 h-4" />
            Closed
          </span>
        );
    }
  };

  const getSeverityBadge = (severity: SeverityLevel) => {
    switch (severity) {
      case 'critical':
        return (
          <span className="inline-flex items-center gap-2 px-3 py-1.5 bg-red-100 text-red-700 rounded-lg border-2 border-red-400 uppercase">
            <Zap className="w-4 h-4" />
            Critical
          </span>
        );
      case 'high':
        return (
          <span className="inline-flex items-center gap-2 px-3 py-1.5 bg-amber-100 text-amber-700 rounded-lg border border-amber-300 uppercase">
            <AlertTriangle className="w-4 h-4" />
            High
          </span>
        );
      case 'medium':
        return (
          <span className="px-3 py-1.5 bg-yellow-100 text-yellow-700 rounded-lg uppercase">
            Medium
          </span>
        );
      case 'low':
        return (
          <span className="px-3 py-1.5 bg-blue-50 text-blue-600 rounded-lg uppercase">
            Low
          </span>
        );
    }
  };

  const getSignalSeverityColor = (severity: string) => {
    switch (severity) {
      case 'critical':
        return 'bg-red-50 border-red-300 text-red-700';
      case 'high':
        return 'bg-amber-50 border-amber-300 text-amber-700';
      case 'medium':
        return 'bg-yellow-50 border-yellow-300 text-yellow-700';
      case 'low':
        return 'bg-blue-50 border-blue-300 text-blue-700';
      default:
        return 'bg-slate-50 border-slate-300 text-slate-700';
    }
  };

  const getTimelineIcon = (iconType: string) => {
    switch (iconType) {
      case 'alert':
        return <AlertTriangle className="w-5 h-5 text-red-600" />;
      case 'create':
        return <FileWarning className="w-5 h-5 text-amber-600" />;
      case 'notification':
        return <Radio className="w-5 h-5 text-blue-600" />;
      case 'review':
        return <Eye className="w-5 h-5 text-purple-600" />;
      default:
        return <Activity className="w-5 h-5 text-slate-600" />;
    }
  };

  return (
    <div className="min-h-screen bg-slate-50">
      {/* Header */}
      <header className="bg-white border-b border-slate-200 sticky top-0 z-10">
        <div className="px-6 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <button
                onClick={onBack}
                className="p-2 hover:bg-slate-100 rounded-lg transition-colors"
              >
                <ArrowLeft className="w-5 h-5 text-slate-600" />
              </button>
              <div>
                <div className="flex items-center gap-3 mb-1">
                  <h1 className="text-slate-900">Alert Detail</h1>
                  <span className="px-2 py-1 bg-blue-100 text-blue-700 text-xs rounded border border-blue-200">
                    REVIEW BEFORE ACTION
                  </span>
                </div>
                <p className="text-slate-600 text-sm">
                  {alert.alertId} · Detected {alert.detectedMinutesAgo} minutes ago
                </p>
              </div>
            </div>

            {/* Quick Status Indicators */}
            <div className="flex items-center gap-3">
              {getSeverityBadge(alert.severity)}
              {getStatusBadge(alert.status)}
            </div>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="px-6 py-6">
        <div className="max-w-[1600px] mx-auto">
          <div className="grid grid-cols-3 gap-6">
            {/* Left Column - Main Info */}
            <div className="col-span-2 space-y-6">
              {/* Alert Summary Panel */}
              <div className="bg-gradient-to-br from-red-50 to-amber-50 rounded-lg border-2 border-red-200 shadow-sm p-6">
                <div className="flex items-start gap-3 mb-4">
                  <div className="p-3 bg-red-600 rounded-lg">
                    <AlertTriangle className="w-6 h-6 text-white" />
                  </div>
                  <div className="flex-1">
                    <h2 className="text-slate-900 mb-2">{alert.alertType}</h2>
                    <p className="text-slate-700 mb-3">{alert.description}</p>
                    <div className="flex items-center gap-2 text-sm text-slate-600">
                      <Clock className="w-4 h-4" />
                      <span>Detected at {alert.detectedAt} ({alert.detectedMinutesAgo} minutes ago)</span>
                    </div>
                  </div>
                </div>

                {/* Risk Summary Metrics */}
                <div className="grid grid-cols-4 gap-3 pt-4 border-t-2 border-red-300">
                  <div className="px-3 py-2 bg-white rounded-lg border border-red-200">
                    <div className="text-xs text-slate-600 mb-1">Penalty Exposure</div>
                    <div className="flex items-center gap-1">
                      <DollarSign className="w-4 h-4 text-red-600" />
                      <span className="text-red-700 font-medium">{alert.riskSummary.totalPenaltyExposure}</span>
                    </div>
                  </div>
                  <div className="px-3 py-2 bg-white rounded-lg border border-red-200">
                    <div className="text-xs text-slate-600 mb-1">Deliveries at Risk</div>
                    <div className="text-red-700 font-medium text-lg">
                      {alert.riskSummary.totalDeliveriesAtRisk}
                    </div>
                  </div>
                  <div className="px-3 py-2 bg-white rounded-lg border border-red-200">
                    <div className="text-xs text-slate-600 mb-1">Worst SLA</div>
                    <div className="flex items-center gap-1">
                      <Clock className="w-4 h-4 text-red-600" />
                      <span className="text-red-700 font-medium">{alert.riskSummary.worstTimeToBreachMinutes}m</span>
                    </div>
                  </div>
                  <div className="px-3 py-2 bg-white rounded-lg border border-red-200">
                    <div className="text-xs text-slate-600 mb-1">VIP Affected</div>
                    <div className="text-red-700 font-medium text-lg">
                      {alert.riskSummary.affectedVIPCount}
                    </div>
                  </div>
                </div>
              </div>

              {/* Impacted Entities Section */}
              <div className="bg-white rounded-lg border border-slate-200 shadow-sm p-6">
                <h2 className="text-slate-900 mb-4">Impacted Entities</h2>

                {/* Routes */}
                <div className="mb-6">
                  <div className="flex items-center gap-2 mb-3">
                    <Route className="w-4 h-4 text-slate-600" />
                    <h3 className="text-sm text-slate-700 font-medium">Affected Routes ({alert.impactedRoutes.length})</h3>
                  </div>
                  <div className="space-y-2">
                    {alert.impactedRoutes.map((route) => (
                      <div
                        key={route.id}
                        className="p-4 bg-amber-50 border border-amber-200 rounded-lg"
                      >
                        <div className="flex items-center justify-between mb-2">
                          <button
                            onClick={() => onOpenRoute?.(route.id)}
                            className="text-blue-600 hover:underline font-medium"
                          >
                            {route.id}
                          </button>
                          <span className="px-2 py-1 bg-amber-100 text-amber-700 text-xs rounded border border-amber-300 uppercase">
                            {route.status}
                          </span>
                        </div>
                        <div className="grid grid-cols-2 gap-4 text-sm">
                          <div className="flex items-center gap-2">
                            <TrendingDown className="w-4 h-4 text-amber-600" />
                            <span className="text-slate-700">+{route.delayMinutes} min delay</span>
                          </div>
                          <div className="flex items-center gap-2">
                            <AlertTriangle className="w-4 h-4 text-amber-600" />
                            <span className="text-slate-700">{route.stopsAtRisk} stops at risk</span>
                          </div>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>

                {/* Deliveries */}
                <div className="mb-6">
                  <div className="flex items-center gap-2 mb-3">
                    <Package className="w-4 h-4 text-slate-600" />
                    <h3 className="text-sm text-slate-700 font-medium">Affected Deliveries ({alert.impactedDeliveries.length})</h3>
                  </div>
                  <div className="space-y-2">
                    {alert.impactedDeliveries.map((delivery) => (
                      <div
                        key={delivery.id}
                        className={`p-4 rounded-lg border-2 ${
                          delivery.priorityLevel === 'vip'
                            ? 'bg-purple-50 border-purple-300'
                            : 'bg-amber-50 border-amber-200'
                        }`}
                      >
                        <div className="flex items-start justify-between mb-2">
                          <div>
                            <button
                              onClick={() => onOpenDelivery?.(delivery.id)}
                              className="text-blue-600 hover:underline font-medium mb-1"
                            >
                              {delivery.id}
                            </button>
                            <div className="text-sm text-slate-700">{delivery.customerName}</div>
                            <div className="text-xs text-slate-600 font-mono mt-1">{delivery.stopId}</div>
                          </div>
                          <div className="text-right">
                            {delivery.priorityLevel === 'vip' && (
                              <span className="inline-block px-2 py-1 bg-purple-600 text-white text-xs rounded mb-2">
                                VIP
                              </span>
                            )}
                            {delivery.priorityLevel === 'high' && (
                              <span className="inline-block px-2 py-1 bg-amber-600 text-white text-xs rounded mb-2">
                                HIGH
                              </span>
                            )}
                          </div>
                        </div>
                        <div className="grid grid-cols-2 gap-4 text-sm pt-3 border-t border-current/20">
                          <div>
                            <div className="text-xs text-slate-600 mb-1">SLA Window</div>
                            <div className="text-slate-700">{delivery.slaWindow}</div>
                          </div>
                          <div>
                            <div className="text-xs text-slate-600 mb-1">Time to Breach</div>
                            <div className="flex items-center gap-1">
                              {delivery.timeToBreachMinutes < 30 ? (
                                <>
                                  <AlertTriangle className="w-4 h-4 text-red-600" />
                                  <span className="text-red-700 font-medium">{delivery.timeToBreachMinutes}m</span>
                                </>
                              ) : (
                                <>
                                  <Clock className="w-4 h-4 text-amber-600" />
                                  <span className="text-amber-700">{delivery.timeToBreachMinutes}m</span>
                                </>
                              )}
                            </div>
                          </div>
                        </div>
                        <div className="flex items-center gap-4 text-xs text-slate-600 mt-3 pt-3 border-t border-current/20">
                          {delivery.penaltyExposure && (
                            <div className="flex items-center gap-1 text-red-700">
                              <DollarSign className="w-3 h-3" />
                              <span>{delivery.penaltyExposure} penalty</span>
                            </div>
                          )}
                          {delivery.contractValue && (
                            <div className="flex items-center gap-1">
                              <span>{delivery.contractValue}</span>
                            </div>
                          )}
                        </div>
                      </div>
                    ))}
                  </div>
                </div>

                {/* Drivers */}
                <div>
                  <div className="flex items-center gap-2 mb-3">
                    <User className="w-4 h-4 text-slate-600" />
                    <h3 className="text-sm text-slate-700 font-medium">Affected Drivers ({alert.impactedDrivers.length})</h3>
                  </div>
                  <div className="space-y-2">
                    {alert.impactedDrivers.map((driver) => (
                      <div
                        key={driver.id}
                        className="p-4 bg-blue-50 border border-blue-200 rounded-lg"
                      >
                        <div className="flex items-center justify-between">
                          <div>
                            <button
                              onClick={() => onOpenDriver?.(driver.id)}
                              className="text-blue-600 hover:underline font-medium mb-1"
                            >
                              {driver.name}
                            </button>
                            <div className="text-xs text-slate-600 font-mono">{driver.id}</div>
                          </div>
                          <div className="text-right">
                            <span className="px-2 py-1 bg-blue-100 text-blue-700 text-xs rounded border border-blue-300 uppercase">
                              {driver.status}
                            </span>
                            <div className="text-xs text-slate-600 mt-2">{driver.currentLoad}</div>
                          </div>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              </div>

              {/* Evidence & Context Panel */}
              <div className="bg-white rounded-lg border border-slate-200 shadow-sm p-6">
                <div className="flex items-center gap-2 mb-4">
                  <Activity className="w-5 h-5 text-slate-600" />
                  <h2 className="text-slate-900">Evidence & Context</h2>
                </div>

                <div className="mb-4 pb-4 border-b border-slate-200">
                  <div className="text-xs text-slate-600 mb-1">Snapshot Time</div>
                  <div className="flex items-center gap-2 text-sm text-slate-900">
                    <Calendar className="w-4 h-4 text-slate-600" />
                    <span>{alert.evidence.snapshotTime} (at time of detection)</span>
                  </div>
                </div>

                {/* Key Signals */}
                <div className="mb-6">
                  <h3 className="text-sm text-slate-700 font-medium mb-3">Key Signals Contributing to Alert</h3>
                  <div className="space-y-3">
                    {alert.evidence.keySignals.map((signal) => (
                      <div
                        key={signal.id}
                        className={`p-4 rounded-lg border ${getSignalSeverityColor(signal.severity)}`}
                      >
                        <div className="flex items-start justify-between mb-2">
                          <div className="font-medium text-sm">{signal.label}</div>
                          <span className="px-2 py-0.5 rounded text-xs border bg-white border-current uppercase">
                            {signal.severity}
                          </span>
                        </div>
                        <div className="text-sm mb-2 font-medium">{signal.value}</div>
                        <div className="flex items-start gap-2 text-xs pt-2 border-t border-current/20">
                          <Info className="w-3 h-3 flex-shrink-0 mt-0.5" />
                          <span>{signal.explanation}</span>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>

                {/* System Notes */}
                <div>
                  <h3 className="text-sm text-slate-700 font-medium mb-3">System Notes</h3>
                  <div className="p-4 bg-slate-50 border border-slate-200 rounded-lg">
                    <ul className="space-y-2">
                      {alert.evidence.systemNotes.map((note, index) => (
                        <li key={index} className="text-sm text-slate-700 flex items-start gap-2">
                          <span className="text-slate-400 mt-1">•</span>
                          <span>{note}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>
              </div>
            </div>

            {/* Right Column - Timeline & Actions */}
            <div className="space-y-6">
              {/* Timeline of Alert */}
              <div className="bg-white rounded-lg border border-slate-200 shadow-sm p-6">
                <div className="flex items-center gap-2 mb-4">
                  <Clock className="w-5 h-5 text-slate-600" />
                  <h2 className="text-slate-900">Alert Timeline</h2>
                </div>

                <div className="space-y-4">
                  {alert.timeline.map((event, index) => (
                    <div key={event.id} className="flex items-start gap-3">
                      <div className="relative">
                        <div className={`p-2 rounded-lg ${
                          event.status === 'current' 
                            ? 'bg-blue-100 border-2 border-blue-500' 
                            : 'bg-slate-100'
                        }`}>
                          {getTimelineIcon(event.icon)}
                        </div>
                        {index < alert.timeline.length - 1 && (
                          <div className="absolute top-10 left-1/2 -translate-x-1/2 w-px h-8 bg-slate-200" />
                        )}
                      </div>
                      <div className="flex-1 pb-2">
                        <div className="flex items-center justify-between mb-1">
                          <span className={`text-sm font-medium ${
                            event.status === 'current' 
                              ? 'text-blue-700' 
                              : 'text-slate-900'
                          }`}>
                            {event.event}
                          </span>
                          <span className="text-xs text-slate-500">{event.timestamp}</span>
                        </div>
                        <p className="text-sm text-slate-600">{event.description}</p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              {/* Navigation Actions */}
              <div className="bg-slate-100 rounded-lg border border-slate-300 p-6">
                <h3 className="text-slate-900 mb-4 text-sm">Investigation & Actions</h3>
                <div className="space-y-3">
                  {alert.impactedRoutes.map((route) => (
                    <button
                      key={route.id}
                      onClick={() => onOpenRoute?.(route.id)}
                      className="w-full flex items-center justify-between px-4 py-3 bg-white border border-slate-300 rounded-lg hover:bg-slate-50 transition-colors"
                    >
                      <div className="flex items-center gap-3">
                        <Route className="w-5 h-5 text-slate-600" />
                        <div className="text-left">
                          <div className="text-slate-900 text-sm">View Route Detail</div>
                          <div className="text-slate-600 text-xs">{route.id}</div>
                        </div>
                      </div>
                      <ChevronRight className="w-5 h-5 text-slate-400" />
                    </button>
                  ))}

                  {alert.impactedDeliveries.slice(0, 2).map((delivery) => (
                    <button
                      key={delivery.id}
                      onClick={() => onOpenDelivery?.(delivery.id)}
                      className="w-full flex items-center justify-between px-4 py-3 bg-white border border-slate-300 rounded-lg hover:bg-slate-50 transition-colors"
                    >
                      <div className="flex items-center gap-3">
                        <Package className="w-5 h-5 text-slate-600" />
                        <div className="text-left">
                          <div className="text-slate-900 text-sm">View Delivery Detail</div>
                          <div className="text-slate-600 text-xs">{delivery.id}</div>
                        </div>
                      </div>
                      <ChevronRight className="w-5 h-5 text-slate-400" />
                    </button>
                  ))}

                  <div className="pt-3 border-t border-slate-300">
                    <button
                      onClick={onOpenRecovery}
                      className="w-full flex items-center justify-between px-4 py-3 bg-amber-600 text-white rounded-lg hover:bg-amber-700 transition-colors border-2 border-amber-700"
                    >
                      <div className="flex items-center gap-3">
                        <AlertTriangle className="w-5 h-5" />
                        <div className="text-left">
                          <div className="font-medium text-sm">Enter Recovery Mode</div>
                          <div className="text-amber-100 text-xs">Review intervention options</div>
                        </div>
                      </div>
                      <Navigation className="w-5 h-5" />
                    </button>
                  </div>
                </div>
              </div>

              {/* Info Panel */}
              <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
                <div className="flex items-start gap-3">
                  <Info className="w-5 h-5 text-blue-600 flex-shrink-0 mt-0.5" />
                  <div>
                    <div className="text-blue-900 text-sm font-medium mb-1">Evidence-Driven Review</div>
                    <p className="text-blue-700 text-sm">
                      This screen provides complete alert context for informed decision-making.
                      Review all evidence before entering Recovery or taking any execution actions.
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
